spring.application.name=Ticketing

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ticketing_db}
spring.datasource.username=${DB_USER:ticketing}
spring.datasource.password=${DB_PASSWORD:ticketing}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true


grpc.server.port=9090