spring.application.name=booking-service

# Booking's own HTTP port ? MUST differ from Events' 8080, since both run at once
server.port=8081

# where Events' gRPC server lives ? this is the phone number Booking dials.
# "events" is a name we'll reference when injecting the stub.
grpc.client.events.address=static://localhost:9090
grpc.client.events.negotiation-type=plaintext

spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=${DB_USER:greatadams}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#kafka broker (finance-kafka container on 9092)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer